name: Rust Test

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.88.0
      - uses: Swatinem/rust-cache@v2
      - name: Run workspace tests
        run: cargo test --workspace
